export interface FabricEventJs {
  type: 'peer-connected' | 'peer-disconnected' | 'roster-updated' | 'message' | 'path-changed'
  endpointId?: string
  from?: string
  data?: Buffer
  status?: 'direct' | 'relay' | 'unknown'
}

/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * dweb fabric：应用级组网的 Node SDK 入口。
 * 工厂：Fabric.createRoot / Fabric.open / Fabric.attach；完成后调用 shutdown 释放资源。
 */
export declare class Fabric {
  /** 创建新 fabric（本节点成为 root，可签发邀请与撤销）。 */
  static createRoot(opts: FabricOptions): Promise<Fabric>
  /** 打开已有 fabric（数据目录已含名册）。 */
  static open(opts: FabricOptions): Promise<Fabric>
  /** 以加入者身份起步（空名册；随后调用 join 兑换邀请）。 */
  static attach(opts: FabricOptions, fabricIdHex: string): Promise<Fabric>
  /** 一步加入：从令牌解析 fabric_id，attach + 兑换 + 持久化名册。 */
  static joinWithToken(opts: FabricOptions, token: string): Promise<Fabric>
  /** 本节点 EndpointId（z-base-32，52 字符） */
  get endpointId(): string
  /** fabric id（hex） */
  fabricIdHex(): Promise<string>
  /** 当前有效成员投影 */
  members(): Promise<Array<Member>>
  /** 查询 EndpointId 是否为有效成员 */
  isMember(endpointId: string): Promise<boolean>
  /** 签发邀请令牌（root-only）。返回 dweb1. 前缀的自包含字符串。 */
  invite(ttlMs: number, recipient?: string | undefined | null): Promise<string>
  /** 兑换邀请令牌加入 fabric（issuer-online 单次兑换）。 */
  join(token: string): Promise<void>
  /** 连接成员（常规通道；双向门控 + 名册同步）。幂等（活跃连接直接成功）。 */
  connect(endpointId: string): Promise<void>
  /** 断开与某成员的会话 */
  disconnect(endpointId: string): Promise<void>
  /** 发送不透明二进制 envelope */
  send(endpointId: string, data: Buffer): Promise<void>
  /** 撤销成员（root-only）；投影收紧并断开既有会话。 */
  revoke(endpointId: string): Promise<void>
  /** 设置本节点显示名 */
  setDisplayName(name: string): Promise<void>
  /** 查询与某成员的当前路径类型："direct" | "relay" | "unknown" */
  linkStatus(endpointId: string): Promise<string>
  /**
   * 注册事件回调（可多次调用，多个回调都会收到全部事件）。
   * 事件对象见 FabricEventJs：{ type, endpointId?, from?, data?, status? }
   */
  on(callback: (event: FabricEventJs) => void): void
  /** 优雅关闭：断开全部会话并释放网络资源。幂等。 */
  shutdown(): Promise<void>
}

/** Fabric 构造配置 */
export interface FabricOptions {
  /** 数据目录（身份密钥与名册持久化位置） */
  dataDir: string
  relay?: RelayOptions
  /** 写入邀请令牌的 issuer 直连地址（host:port） */
  advertiseAddrs?: Array<string>
}

/** 成员信息 */
export interface Member {
  endpointId: string
  displayName?: string
  sinceMs: number
}

/** SDK 原生层版本 */
export declare function nativeVersion(): string

/** relay 配置 */
export interface RelayOptions {
  /** "disabled" | "custom" | "n0"（默认 "n0"） */
  mode?: string
  /** mode = "custom" 时的 relay URL 列表（自托管 docker 或其它 iroh relay） */
  urls?: Array<string>
}
