// napi 生成的 d.ts 后处理：把原生签名改写为 C0 契约形态
// （openspec/changes/connectivity-ux-hardening/contracts/client-sdk.d.ts.md）。
// index.js 包装层改变了两处可见签名：
//   - on() 原生返回回调 id（number）；包装后返回取消订阅函数 () => void
//   - 事件以 JSON 字符串投递；包装后是类型化事件对象（判别联合）
import * as fs from "node:fs";

import { fileURLToPath } from "node:url";
const p = fileURLToPath(new URL("../index.d.ts", import.meta.url));
// 网络磁盘（SMB）页缓存会让文本读拿到旧内容（实证：stat 13559 vs utf8 读 9733，
// 旧缓存被归一化后再写回即产生重复块）。二进制读走不同缓存路径，绕开该问题。
let s = fs.readFileSync(p).toString("utf8");
// 归一化（幂等前提）：napi 生成块与注入头可能因历史多次运行而重复——
// 以首个 napi 头为锚，保留其前的注入头一份 + 首个 napi 块，删除后续重复。
{
  const NAPI = "/* auto-generated by NAPI-RS */";
  const positions = [];
  let at = s.indexOf(NAPI);
  while (at >= 0) {
    positions.push(at);
    at = s.indexOf(NAPI, at + NAPI.length);
  }
  if (positions.length > 1) {
    // 保留首块（注入头之后的第一份），截断后续重复块
    s = s.slice(0, positions[1]);
  }
  // 注入头（FabricEventJs 块）同样去重：保留第一份
  const MARK = "/** 事件判别联合：relay-* 事件必携带完整快照 payload（非可选） */";
  const m1 = s.indexOf(MARK);
  if (m1 >= 0) {
    const m2 = s.indexOf(MARK, m1 + MARK.length);
    if (m2 >= 0) s = s.slice(0, m2) + s.slice(m2).split(MARK).slice(1).join("").replace(/^\n/, "");
  }
}
s = s.replaceAll("=> any", "=> void");
// on：error-first 字符串回调 → 类型化事件对象；返回取消订阅函数
s = s.replace(
  /on\(callback: [^\n]*\): number/,
  "on(callback: (event: FabricEventJs) => void): () => void",
);
// 事件判别联合（relay-* 必携带快照 payload）+ RelayStatusJs 同构快照
if (!s.includes("export type FabricEventJs")) {
  s = `/** 事件判别联合：relay-* 事件必携带完整快照 payload（非可选） */
export type FabricEventJs =
  | {
      type: 'peer-connected' | 'peer-disconnected'
      endpointId: string
    }
  | { type: 'roster-updated' }
  | { type: 'message'; from: string; data: Buffer }
  | { type: 'path-changed'; endpointId: string; status: 'direct' | 'relay' | 'unknown' }
  | { type: 'relay-online' | 'relay-offline'; relay: RelayStatusJs }

/** relay 状态快照（relayStatus() 返回值与 relay-* 事件 payload 同构） */
export interface RelayStatusJs {
  /** 字面量联合（非 string） */
  mode: 'disabled' | 'custom' | 'n0'
  /** 配置的 relay URL 列表（disabled 为空数组；n0 恒为 ["https://relay.iroh.network"]） */
  urls: string[]
  /** null <=> mode === "disabled"；否则为任一 relay 已连接 */
  online: boolean | null
  /** 最近一次连接错误类别（脱敏：无凭证段；无错误为 null） */
  lastError: string | null
}

` + s;
}
// httpProxy：napi Either<string, HttpProxyUrl> → 契约判别联合
s = s.replace(
  /httpProxy\?: string \| HttpProxyUrl/,
  "httpProxy?: 'none' | 'from-env' | { url: string }",
);
// 唯一声明（P1-1，确定性重写）：删除 napi 生成的宽松尾部块后重写为契约形态
{
  const tailStart = s.indexOf("/**\n * relay 配置（判别联合的 napi 投影）");
  if (tailStart >= 0) {
    const tailEnd = s.indexOf("}\n", s.indexOf("export interface RelayStatusJs"));
    s =
      s.slice(0, tailStart) +
      `/** relay 配置（判别联合：非法组合构造期拒绝） */
export type RelayOptions =
  | { mode?: 'n0' }
  | { mode: 'disabled' }
  | { mode: 'custom'; urls: [string, ...string[]] }
` +
      s.slice(tailEnd + 2);
  }
}
// relayStatus：index.js 包装为 async → Promise（P1-1）
s = s.replace("relayStatus(): RelayStatusJs", "relayStatus(): Promise<RelayStatusJs>");
// P1-3（R3）：导出 HttpProxyOptions 公共别名 + deriveErrorCode 声明
if (!s.includes("export type HttpProxyOptions")) {
  s = s.replace(
    "export type FabricEventJs =",
    `/** 代理策略：none=直连；from-env=读环境代理；url 形态仅 SDK 使用 */
export type HttpProxyOptions = 'none' | 'from-env' | { url: string }

/** 从 SDK 错误消息的 [<kebab-code>] 前缀派生稳定错误码（SCREAMING_SNAKE）；无前缀返回 null */
export declare function deriveErrorCode(message: string): string | null

export type FabricEventJs =`,
  );
}
// 终截断：注入/变换可能重新引入 NAPI 标记重复（注入头本身不含，但历史运行
// 的脏输入会），写入前最后执行一次位置截断保证唯一。
{
  const NAPI = "/* auto-generated by NAPI-RS */";
  const second = s.indexOf(NAPI, s.indexOf(NAPI) + NAPI.length);
  if (second >= 0) {
    s = s.slice(0, second).trimEnd() + "\n";
  }
}
fs.writeFileSync(p, Buffer.from(s, "utf8"));
console.log("index.d.ts fixed");
